module.exports = {
	bitoex: [
		"BTC",
	],
	bitfinex: [
		"BTC", "LTC", "ETH", "ETC", "RRT",
		"ZEC", "XMR", "DSH", "BCC", "BCU",
		"XRP", "IOT", "EOS", "SAN", "OMG",
		"BCH", "NEO", "ETP", "BTG",
	],
	bittrex: [
		"LTC", "DOGE", "VTC", "PPC", "FTC",
		"RDD", "NXT", "DASH", "POT", "BLK",
		"EMC2", "XMY", "AUR", "EFL", "GLD",
		"SLR", "PTC", "GRS", "NLG", "RBY",
		"XWC", "MONA", "THC", "ENRG", "ERC",
		"VRC", "CURE", "XMR", "CLOAK", "START",
		"KORE", "XDN", "TRUST", "NAV", "XST",
		"BTCD", "VIA", "UNO", "PINK", "IOC",
		"CANN", "SYS", "NEOS", "DGB", "BURST",
		"EXCL", "SWIFT", "DOPE", "BLOCK", "ABY",
		"BYC", "XMG", "BLITZ", "BAY", "BTS",
		"FAIR", "SPR", "VTR", "XRP", "GAME",
		"COVAL", "NXS", "XCP", "BITB", "GEO",
		"FLDC", "GRC", "FLO", "NBT", "MUE",
		"XEM", "CLAM", "DMD", "GAM", "SPHR",
		"OK", "SNRG", "PKB", "CPC", "AEON",
		"ETH", "GCR", "TX", "BCY", "EXP",
		"INFX", "OMNI", "AMP", "AGRS", "XLM",
		"BTA", /*"BTC"*/, "CLUB", "VOX", "EMC",
		"FCT", "MAID", "EGC", "SLS", "RADS",
		"DCR", "SAFEX", "BSD", "XVG", "PIVX",
		"XVC", "MEME", "STEEM", "2GIVE", "LSK",
		"PDC", "BRK", "DGD", "DGD", "WAVES",
		"RISE", "LBC", "SBD", "BRX", "DRACO",
		"ETC", "ETC", "STRAT", "UNB", "SYNX",
		"TRIG", "EBST", "VRM", "SEQ", "XAUR",
		"SNGLS", "REP", "SHIFT", "ARDR", "XZC",
		"NEO", "ZEC", "ZCL", "IOP", "DAR",
		"GOLOS", "UBQ", "KMD", "GBG", "SIB",
		"ION", "LMC", "QWARK", "CRW", "SWT",
		"TIME", "MLN", "ARK", "DYN", "TKS",
		"MUSIC", "DTB", "INCNT", "GBYTE", "GNT",
		"NXC", "EDG", "LGD", "TRST", "GNT",
		"REP", "ETH", "WINGS", "WINGS", "RLC",
		"GNO", "GUP", "LUN", "GUP", "RLC",
		"LUN", "SNGLS", "GNO", "APX", "TKN",
		"TKN", "HMQ", "HMQ", "ANT", "TRST",
		"ANT", "SC", "BAT", "BAT", "ZEN",
		"1ST", "QRL", "1ST", "QRL", "CRB",
		"CRB", "LGD", "PTOY", "PTOY", "MYST",
		"MYST", "CFI", "CFI", "BNT", "BNT",
		"NMR", "NMR", "TIME", "LTC", "XRP",
		"SNT", "SNT", "DCT", "XEL", "MCO",
		"MCO", "ADT", "ADT", "FUN", "FUN",
		"PAY", "PAY", "MTL", "MTL", "STORJ",
		"STORJ", "ADX", "ADX", "DASH", "SC",
		"ZEC", "ZEC", "LTC", "ETC", "XRP",
		"OMG", "OMG", "CVC", "CVC", "PART",
		"QTUM", "QTUM", "XMR", "XEM", "XLM",
		"NEO", "XMR", "DASH", "BCC", "BCC",
		"BCC", "NEO", "WAVES", "STRAT", "DGB",
		"FCT", "BTS", "OMG",
	],
}
